export declare enum months {
    NISSAN = 1,
    IYAR = 2,
    SIVAN = 3,
    TAMMUZ = 4,
    AV = 5,
    ELUL = 6,
    TISHREI = 7,
    CHESVAN = 8,
    KISLEV = 9,
    TEVET = 10,
    SHEVAT = 11,
    ADAR_I = 12,
    ADAR_II = 13,
}
